### ISSUE TITLE
How to handle the missing genotypes (./.)?

### ISSUE THREAD

**Issue by hui-liu** [thamala/cacaoSV#1]
Hi thamala,

When combining SV calls from MUM&Co into a VCF file using mumco2vcf, did you convert the ".|." into "0|0" (https://github.com/thamala/cacaoSV/blob/main/mumco2vcf.c#L560)?

Best,
Hui

**Comment by thamala** [comment]
Mum&co doesn’t produce missing genotypes, so if an SV is present in some samples but missing in others, it's assumed to correspond to the reference genome in the missing ones. This assumption can be wrong if the assemblies have gaps in those areas, but that needs to be checked separately.
